### ISSUE TITLE
Decimals not consistent 

### ISSUE THREAD

**Issue by nihonjin98** [DavidFW1960/bom-weather-card#65]
[](url)Hi is there anyway I can fix up how my decials are displaying.  I have show_decimals = true set.

But for some reason my main temp is showing 2 decimals places (23.61).  The feels like is showing correctly (26.5).  My today high and low are not showing any decimals (26 and 20).  My rain total is showing 2 decimals (62.71).  

I would like for all deicmals to be set to 1 decimal place if possible.  Can this be something i can edit and fix for my instance only or should it already be set like this and something is going wrong?

![weather](https://user-images.githubusercontent.com/91408068/143180555-111d519a-909a-4abf-9289-33e95d25d960.jpg)

**Comment by DavidFW1960** [comment]
What is the state of the current temp being parsed from HA?

**Comment by DavidFW1960** [comment]
checking the code if show decimals isn't set than it uses the math.round function to round to an integer. So when it doesn't round it will be using the state as is from HA's state..

**Comment by nihonjin98** [comment]
> What is the state of the current temp being parsed from HA?

HA has the state showing 2 decimal places.

**Comment by nihonjin98** [comment]
> checking the code if show decimals isn't set than it uses the math.round function to round to an integer. So when it doesn't round it will be using the state as is from HA's state..

I do have show decimal set as true in the card yaml code.

**Comment by DavidFW1960** [comment]
> > What is the state of the current temp being parsed from HA?
> 
> HA has the state showing 2 decimal places.

Yeah that is why it's showing 2 decimals on the card. It just shows what you are parsing through. I'd suggest using a template sensor in HA and then parsing that entity through with 1 decimal place

**Comment by nihonjin98** [comment]
I can create templates thanks for the solution.  But what about those values that are not even showing with decimals it seems that for some reason the show decimals is not applying to the Today's High and Low values.

**Comment by DavidFW1960** [comment]
do they have decimals in the state in HA?

**Comment by DavidFW1960** [comment]
I am definitely rounding those... Does the HA stste include decimal places? I can fairly easily fix that if the state includes it..

**Comment by DavidFW1960** [comment]
i think I can specify rounding to 1 place as well so no need for a template sensor for that....

**Comment by nihonjin98** [comment]
> do they have decimals in the state in HA?

Yes they do but were not showing with decimals in the card as they were rounding to whole integer.

**Comment by nihonjin98** [comment]
> 

That would be great even if you could set in the card to round to either 0 for now rounding or 1 or 2 decimals to cater for what others may like.  not sure how hard it would be to do.

**Comment by nihonjin98** [comment]
> i think I can specify rounding to 1 place as well so no need for a template sensor for that....

That would be great even if you could set in the card to round to either 0 for no decimals or 1 or 2 decimals to cater for what others may like. not sure how hard it would be to do.  If only 1 option i think 1 decimal is best as anything more than that would be over kill for weather.

**Comment by DavidFW1960** [comment]
Ok. It will take a couple of days and I'll release as a beta. Stand by.

**Comment by DavidFW1960** [comment]
I'm still working on this but it's not cooperating at the moment.

**Comment by nihonjin98** [comment]
Thank you.

**Comment by DavidFW1960** [comment]
ok I just pushed an updated js file that will fix the decimal places to 1 place for apparent temp and also current temp. If you use HACS you can pull the master instead or 0.90a. It will report as version 0.91. if you aren't using HACS, just download the raw js file and do a clear cache/hard reload in HA you should see version 0.91 in the console in HA if you have the right version. Still working with min/max temps but I can fix this I am sure. No need for templates or any other changes on your end. Please lst me know if not working.

**Comment by DavidFW1960** [comment]
ok I think it's working but can you test results are as expected as per above

**Comment by nihonjin98** [comment]
Thank you I will try it out today and let you know.  Thank you for taking the time to look into this.

**Comment by DavidFW1960** [comment]
So I just found a weird console error that I fixed to pull the latest. There is still a console error that I can't understand but it might be in the card before anyway so it could be a frontend issue but the card seems to be working properly to me. Interested in your feedback.

**Comment by nihonjin98** [comment]
Everything is showing correct to 1 decimal place for me except for the entity_pop_intensity number.  It still shows with 2 decimal places.  Otherwise I do not get any errors and all is working ok for me.

**Comment by DavidFW1960** [comment]
is that coming from HA with that state because I have not touched that with any rounding at all?

**Comment by DavidFW1960** [comment]
it would actually be much better if I don't screw with that because if I fix it to 1 place then it will display 0.0 instead of just 0..... it will show that to 1 decimal lace even if show decimals is off. I only apply the show_decimals to temperature entities everything else is 0 places like pressure but the pop etc are how they come from HA.

**Comment by DavidFW1960** [comment]
![image](https://user-images.githubusercontent.com/36390762/145500226-eaaa085c-cf1b-4a0a-97d3-3aff1570b410.png)
that is a range for predicted straight from BOM
the one you menton
```
entity_pop_intensity: sensor.gosford_rain_since_9am
```
That is an actual as well straight from BOM
![image](https://user-images.githubusercontent.com/36390762/145500404-a97b7604-934a-4a0d-af8b-b938231386a1.png)

So if it's showing 2 decimal places for you it must be coming from BOM and will be in your state 

If that's the case then you should use a Template sensor to fix what is parsed as the law of unintended consequences will bite me on the arse as per the above.

**Comment by DavidFW1960** [comment]
Can you pull the latest master of this and make sure i have nit screwed this up before i release a new beta tomorrow

**Comment by nihonjin98** [comment]
Will do. I'll let you know how it goes.

Thanks
________________________________

**Comment by nihonjin98** [comment]
Everything except the Today High and Today Low appear to still show 1 decimal place.  Both Today high and low lost showing the decimal place.  Let me know if you need any more info.

**Comment by DavidFW1960** [comment]
Theres a config option for that. Its in the readme I think. I can check tomorrow if you don't see it.

**Comment by nihonjin98** [comment]
> Theres a config option for that. Its in the readme I think. I can check tomorrow if you don't see it.

It was showing with the decimals already before I updated to your latest master.  I thought you wanted me to check your latest update didnt change anything such as the decimals.  Are you suggesting I need to make a different change to get the decimals back again for todays high and low?

**Comment by nihonjin98** [comment]
Just checked your readme and can see that it now needs the show_decimals_today which is a new flag and to set it to true which i have done and it shows the values with their decimals.  Thanks.

**Comment by DavidFW1960** [comment]
Yeah i think Simons pr requires a config option for it. I will check tomorrow and advise. There was also a but where it didn't show decimals correctly until it refreshed according to simon. Anyway i will check this tomorrow

**Comment by Makin-Things** [comment]
The whole show decimals was a bit of a mess so I cleaned it up and fixed things.  I split the show_decimals into 2 flags as some people use the today fields for forecast temperatures and they are always whole numbers so displaying them with a .0 at the end all the time would probably annoy someone (me!). All of the decimal stuff was broken for people using different locales (where they use different symbols for the decimal and separator ie. German).

**Comment by DavidFW1960** [comment]
Simon we might default show_decimals_today to true so this doesn't become a breaking change.

**Comment by Makin-Things** [comment]
I don't think it is wise to have different defaults for the two flags. Especially when it was broken before anyway. Before this change if you set show_decimals to true and the values where integers then it would not show the decimal part on the card load, but then when it refreshed it would add it in, but not used the correct locale. So I think either way there are going to be some people that might notice a change. So I would prefer to go with consistent settings.

**Comment by DavidFW1960** [comment]
I just hate breaking changes. That always pisses someone off
